### PR TITLE
add registry accessors

### PR DESCRIPTION
**Pull request by mrk-its**
In my https://github.com/mrk-its/bevy-atari emulator project I need to store / restore state of CPU. This PR adds missing accessor methods for cpu registers. It also changes visibility of get_flags / set_flags / StatusFlag to public.

BTW thanks for great project - it is able to successfully run many of Atari XL/XE games / demos (also demanding cycle-exact emulation) - good job! 

Online example: Atari Robbo running in browser: https://mrk.sed.pl/bevy-atari/#disk_1%3D%3Dhttps%3A%2F%2Fatarionline.pl%2Farch%2FR%2FRobbo%20(L.K.%20Avalon)%2FRobbo%20(demo)%20(1989)(L.K.%20Avalon)(PL).xex%7C%7Cosrom%3D%3Dhttps%3A%2F%2Fatarionline.pl%2Futils%2F9.%20ROM-y%2FSystemy%20operacyjne%2FAtari%20OS%20v2%2083.10.05.rom

### CODE REVIEW

**Comment by GarettCooper** [comment]
Thanks again! I have to admit, I'm not a big fan of just making everything public as a solution for the state problem. I'd like to maintain the simplicity of the interface and keep the actual implementation details of the 6502 hidden. As an alternative, maybe we could add an optional serde feature or a pair of functions (also behind a feature) to serialize and deserialize the state of the emulator to a byte buffer. That way you can still save and restore a running programming without adding a bunch of noise to the public interface.

**Comment by mrk-its** [comment]
I like idea of exposing interface to serialization, but unfortunately it do not cover well my current use cases:

1. I need to read efficiently program counter register (PC) to implement breakpoints and 'OS patching' (for example it is very common in atari emulators to patch IO calls to speed up IO significantly). We already have `set_program_counter`, I need at least get_program_counter() for reading current PC. OS patching implementation also needs to read / modify stack_pointer and set cpu registers / flags - I can do serialize / modify / deserialize for that (because it needs to be done only when OS routine has been called, so it doesn't need to be super performant, but it doesn't sound super convenient). Here is example how I'm currently returning from patched OS routine to user program: https://github.com/mrk-its/bevy-atari/blob/671d08193c5e83cf5f60d2ba65e23c02199db109/src/sio.rs#L72

2. Currently I need to know when current cpu instruction completed (I need this to emulate properly interactions with Atari's ANTIC graphics processor) - I'm using remaining_cycles for that (and serialization of course is not solution here because of performance - one possible solution will be changing signature of `MOS6502::cycle` method to return instruction completion status).

**Comment by GarettCooper** [comment]
Okay, interesting. It definitely seems like that accessor functions are the best way forward in that case. If you could add some doc comments to the functions (It's a little redundant in this case but every other function in the module has them) and fix the one formatting error I'll release your changes as `1.1.0`. I think I'll put them behind an `implementation_transparency` feature flag as a compromise to try and maintain simplicity in the standard interface.

**Comment by GarettCooper** [comment]
Oh, and try rebasing to fix the diff issues with the files you haven't touched.

**Comment by mrk-its** [comment]
> Oh, and try rebasing to fix the diff issues with the files you haven't touched.

It seems there is still a lot of files with cr-lf encoding, after introducing `.gitattributes` I see all of them as modified:
```
$ git ls-files --eol
i/lf    w/lf    attr/text eol=lf      	.gitattributes
i/lf    w/lf    attr/text eol=lf      	.gitignore
i/crlf  w/crlf  attr/text eol=lf      	.travis.yml
i/crlf  w/crlf  attr/text eol=lf      	Cargo.toml
i/crlf  w/crlf  attr/text eol=lf      	LICENSE
i/lf    w/lf    attr/text eol=lf      	README.md
i/crlf  w/crlf  attr/text eol=lf      	README.tpl
i/lf    w/lf    attr/text eol=lf      	benches/benches.rs
i/crlf  w/crlf  attr/text eol=lf      	emulator_6502.iml
i/crlf  w/crlf  attr/text eol=lf      	matrix_scraper.py
i/crlf  w/crlf  attr/text eol=lf      	rustfmt.toml
i/lf    w/lf    attr/text eol=lf      	src/address_modes.rs
i/lf    w/lf    attr/text eol=lf      	src/lib.rs
i/lf    w/lf    attr/text eol=lf      	src/opcodes/illegal.rs
i/lf    w/lf    attr/text eol=lf      	src/opcodes/mod.rs
i/lf    w/lf    attr/text eol=lf      	src/test_utilities.rs
i/crlf  w/crlf  attr/text eol=lf      	tests/bins/6502_bench.asm
i/-text w/-text attr/text eol=lf      	tests/bins/6502_bench.bin
i/-text w/-text attr/text eol=lf      	tests/bins/6502_loop_test.bin
i/lf    w/lf    attr/text eol=lf      	tests/tests.rs
```
I've just created separate PR addressing that: https://github.com/GarettCooper/emulator_6502/pull/7

**Comment by mrk-its** [comment]
Done. I also reverted visibility of `get_flag` / `set_flag`  and `StatusFlag` enum back to private.

**Comment by GarettCooper** [comment]
Alright, this looks good. I'll add the feature flag, a BCD integration test, and release 1.1.0

**Pull request merged**
